### ISSUE TITLE
[BUG] Significant prompt processing speed difference when using Tensor Parallelism

### ISSUE THREAD

**Issue by ThomasBaruzier** [turboderp-org/exllamav2#734]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.12

### Pytorch version

2.5.1

### Model

Any, here Llama 3.3 70B

### Describe the bug

Hello!

I benchmarked prompt processing speeds with ExLlamaV2 0.2.8 and noticed a big difference when using Tensor Parallelism (TP). Here are the prompt processing speeds for Llama 3.3 70B at 4.5bpw:

Without Tensor Parallelism:
- Without spec decoding: 1045.8 T/s
- With spec decoding: 1010.34 T/s

With Tensor Parallelism:
- Without spec decoding: 378.87 T/s
- With spec decoding: 374.45 T/s

Test config:
- Context length tested: 16k
- Context cache: Q8
- Context batch size: 2048
- Hardware: 2x RTX 3090 (MSI @ 350W, FE @ 400W)

### Reproduction steps

Benchmarking different configs

### Expected behavior

TP prompt ingestion speeds closer to non TP configs

### Acknowledgements

- [x] I have looked for similar issues before submitting this one.
- [x] I understand that the developers have lives and my issue will be answered when possible.
- [x] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by bold84** [comment]
I can confirm this.

With TP: 7171 new tokens at 210.95 T/s
Without T: 12666 new tokens at 1668.22 T/s

**Comment by gapeleon** [comment]
You're likely bound by PCIe bandwidth between the 2 cards.

What PCIe generation and width are you using?

For reference here's mine using the same 4.5bpw quant with 2x3090:

PCIe 4.0 x16  - 850 T/s
PCIe 4.0 x8    - 600 T/s
PCIe 4.0 x4    - 400 T/s

I get about the same with vllm.

**Comment by bold84** [comment]
hmm... good point.

```bash
  GNU nano 6.2                                                     gpu_info.sh
#!/bin/bash

# Function to calculate PCIe throughput in GB/s
calculate_throughput() {
    local speed=$1
    local width=$2
    echo "scale=2; ($speed * $width * 1/8)" | bc
}

# Function to extract PCIe speed and width
extract_pcie_info() {
    local info=$1
    local speed=$(echo "$info" | grep -A 10 'Express' | grep -oP '(?<=Speed )\d+GT/s' | tr -d 'GT/s' | head -n 1)
    local width=$(echo "$info" | grep -A 10 'Express' | grep -oP '(?<=Width x)\d+' | tr -d 'x' | head -n 1)
    echo "$speed $width"
}

# Get list of GPU slots
gpu_slots=$(lspci | grep -i vga | awk '{print $1}')

# Loop through each GPU slot
for slot in $gpu_slots; do
    # Get detailed information with sudo and verbose output
    info=$(sudo lspci -vv -s $slot)

    # Extract PCIe link speed and width
    read speed width <<< $(extract_pcie_info "$info")

    # Check if speed and width were extracted correctly
    if [[ -z "$speed" || -z "$width" ]]; then
        echo "Failed to extract PCIe information for GPU in slot $slot"
        continue
    fi

    # Calculate throughput
    throughput=$(calculate_throughput $speed $width)

    # Display information
    echo "GPU in slot $slot:"
    echo "PCIe Configuration: $speed GT/s x$width"
    echo "Theoretical Throughput: $throughput GB/s"
    echo
done
```

GPU in slot 01:00.0:
PCIe Configuration: 16 GT/s x16
Theoretical Throughput: 32.00 GB/s

GPU in slot 03:00.0:
PCIe Configuration: 16 GT/s x16
Theoretical Throughput: 32.00 GB/s

GPU in slot 3e:00.0:
PCIe Configuration: 8 GT/s x16
Theoretical Throughput: 16.00 GB/s

**Comment by gapeleon** [comment]
That's just checking the maximum throughput of the slot, rather than the actual negotiated link width being used.
eg. on my rigs with [ 2 cards at 16x, 2 cards at 8x] + [1 card at 16x + 1 card at 4x] it printed 16 GT/s x16 for all of them.

Check `nvtop` if you have it, or I guess:
`nvidia-smi -q  |grep Current |grep x`

Which gives me:
nvidia-smi -q  |grep Current |grep x
Rig1:
                Current                   : 16x
                Current                   : 16x
                Current                   : 8x
                Current                   : 8x
Rig2:

nvidia-smi -q  |grep Current |grep x
                Current                   : 16x
                Current                   : 4x

Your 210.95 T/s looks PCIe 3.0 x4 to me, which is common if you put 3 GPUs in a consumer Intel/AMD board.

**Comment by bold84** [comment]
@gapeleon you're right... 

Current                   : 8x
Current                   : 8x
Current                   : 4x

**Comment by bold84** [comment]
Well, I gotta upgrade then 😎

**Comment by ThomasBaruzier** [comment]
Conducting my own tests, it may seem that the bandwidth is not the primary bottleneck. Here are two videos running prompt ingestion on L3.3 70B 4.5bpw on 2*3090. The first video showcase x4 and x8, the second x8 and x8.

https://github.com/user-attachments/assets/59aff2cd-2448-47cc-a20a-473e26dde46b

Speed: 393.82T/s

https://github.com/user-attachments/assets/7635e1c3-9ab9-433e-9ecf-b5d5d5db73c4

Speed: 622.04T/s

Based on these observations, the data transfer rate remains far from the theoretical maximum, maybe around 4GiB/s and 8GiB/s in average compared to the 8GiB/s and 16GiB/s available.

I don't know quite know ExllamaV2 works under the hoods, and that maybe this is already the maximum we can get out of these cards, but in the case that there is actually an issue, I'd be happy to cooperate regarding tests and reports.

**Comment by ThomasBaruzier** [comment]
> [@ThomasBaruzier](https://github.com/ThomasBaruzier) could you please share the code to reproduce your results?

There is no code, I simply triggered a 500 tokens generation though a curl request, you can also do it from a web UI. Here's the config, though:

```yml
model:
  model_dir: /home/user/storage/quants/exl
  inline_model_loading: false
  use_dummy_models: false
  model_name: Llama-3.3-70B-Instruct-4.5bpw
  use_as_default: ['max_seq_len', 'cache_mode', 'chunk_size']
  max_seq_len: 41216
  tensor_parallel: true
  gpu_split_auto: false
  autosplit_reserve: [0]
  gpu_split: [0,25,25]
  rope_scale:
  rope_alpha:
  cache_mode: Q6
  cache_size:
  chunk_size: 2048
  max_batch_size:
  prompt_template:
  vision: false
  num_experts_per_token:

draft_model:
  draft_model_dir: /home/user/storage/quants/exl
  draft_model_name: Llama-3.2-1B-Instruct-6.0bpw
  draft_rope_scale:
  draft_rope_alpha:
  draft_cache_mode: Q6
  draft_gpu_split: [0,0.9,25]
```
